
'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("ae47735f-5e40-4f51-b4fc-0b5c25daaf55")>
#Region "Contextes"

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
Public Partial Class CardAvoEntities
    Inherits ObjectContext

    #Region "Constructeurs"

    ''' <summary>
    ''' Initialise un nouvel objet CardAvoEntities à l'aide de la chaîne de connexion trouvée dans la section 'CardAvoEntities' du fichier de configuration d'application.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=CardAvoEntities", "CardAvoEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisez un nouvel objet CardAvoEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "CardAvoEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisez un nouvel objet CardAvoEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "CardAvoEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Méthodes partielles"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propriétés ObjectSet"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public ReadOnly Property Adresses() As ObjectSet(Of Adresses)
        Get
            If (_Adresses Is Nothing) Then
                _Adresses = MyBase.CreateObjectSet(Of Adresses)("Adresses")
            End If
            Return _Adresses
        End Get
    End Property

    Private _Adresses As ObjectSet(Of Adresses)

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public ReadOnly Property Avocats() As ObjectSet(Of Avocats)
        Get
            If (_Avocats Is Nothing) Then
                _Avocats = MyBase.CreateObjectSet(Of Avocats)("Avocats")
            End If
            Return _Avocats
        End Get
    End Property

    Private _Avocats As ObjectSet(Of Avocats)

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public ReadOnly Property infodistrict() As ObjectSet(Of infodistrict)
        Get
            If (_infodistrict Is Nothing) Then
                _infodistrict = MyBase.CreateObjectSet(Of infodistrict)("infodistrict")
            End If
            Return _infodistrict
        End Get
    End Property

    Private _infodistrict As ObjectSet(Of infodistrict)

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public ReadOnly Property infomega() As ObjectSet(Of infomega)
        Get
            If (_infomega Is Nothing) Then
                _infomega = MyBase.CreateObjectSet(Of infomega)("infomega")
            End If
            Return _infomega
        End Get
    End Property

    Private _infomega As ObjectSet(Of infomega)

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public ReadOnly Property inhpra() As ObjectSet(Of inhpra)
        Get
            If (_inhpra Is Nothing) Then
                _inhpra = MyBase.CreateObjectSet(Of inhpra)("inhpra")
            End If
            Return _inhpra
        End Get
    End Property

    Private _inhpra As ObjectSet(Of inhpra)

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    Public ReadOnly Property lettremega() As ObjectSet(Of lettremega)
        Get
            If (_lettremega Is Nothing) Then
                _lettremega = MyBase.CreateObjectSet(Of lettremega)("lettremega")
            End If
            Return _lettremega
        End Get
    End Property

    Private _lettremega As ObjectSet(Of lettremega)

    #End Region

    #Region "Méthodes AddTo"

    ''' <summary>
    ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Adresses. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
    ''' </summary>
    Public Sub AddToAdresses(ByVal adresses As Adresses)
        MyBase.AddObject("Adresses", adresses)
    End Sub

    ''' <summary>
    ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Avocats. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
    ''' </summary>
    Public Sub AddToAvocats(ByVal avocats As Avocats)
        MyBase.AddObject("Avocats", avocats)
    End Sub

    ''' <summary>
    ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet infodistrict. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
    ''' </summary>
    Public Sub AddToinfodistrict(ByVal infodistrict As infodistrict)
        MyBase.AddObject("infodistrict", infodistrict)
    End Sub

    ''' <summary>
    ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet infomega. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
    ''' </summary>
    Public Sub AddToinfomega(ByVal infomega As infomega)
        MyBase.AddObject("infomega", infomega)
    End Sub

    ''' <summary>
    ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet inhpra. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
    ''' </summary>
    Public Sub AddToinhpra(ByVal inhpra As inhpra)
        MyBase.AddObject("inhpra", inhpra)
    End Sub

    ''' <summary>
    ''' Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet lettremega. Utilisez la méthode .Add de la propriété ObjectSet(Of T) associée à la place.
    ''' </summary>
    Public Sub AddTolettremega(ByVal lettremega As lettremega)
        MyBase.AddObject("lettremega", lettremega)
    End Sub

    #End Region

End Class

#End Region

#Region "Entités"

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CardAvoModel", Name:="Adresses")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Adresses
    Inherits EntityObject
    #Region "Méthode de fabrique"

    ''' <summary>
    ''' Créez un nouvel objet Adresses.
    ''' </summary>
    ''' <param name="code">Valeur initiale de la propriété code.</param>
    ''' <param name="rowId">Valeur initiale de la propriété RowId.</param>
    Public Shared Function CreateAdresses(code As Global.System.String, rowId As Global.System.Guid) As Adresses
        Dim adresses as Adresses = New Adresses
        adresses.code = code
        adresses.RowId = rowId
        Return adresses
    End Function

    #End Region

    #Region "Propriétés primitives"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property code() As Global.System.String
        Get
            Return _code
        End Get
        Set
            OncodeChanging(value)
            ReportPropertyChanging("code")
            _code = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("code")
            OncodeChanged()
        End Set
    End Property

    Private _code As Global.System.String
    Private Partial Sub OncodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property adresse() As Global.System.String
        Get
            Return _adresse
        End Get
        Set
            OnadresseChanging(value)
            ReportPropertyChanging("adresse")
            _adresse = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("adresse")
            OnadresseChanged()
        End Set
    End Property

    Private _adresse As Global.System.String
    Private Partial Sub OnadresseChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnadresseChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ville() As Global.System.String
        Get
            Return _ville
        End Get
        Set
            OnvilleChanging(value)
            ReportPropertyChanging("ville")
            _ville = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ville")
            OnvilleChanged()
        End Set
    End Property

    Private _ville As Global.System.String
    Private Partial Sub OnvilleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnvilleChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property province() As Global.System.String
        Get
            Return _province
        End Get
        Set
            OnprovinceChanging(value)
            ReportPropertyChanging("province")
            _province = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("province")
            OnprovinceChanged()
        End Set
    End Property

    Private _province As Global.System.String
    Private Partial Sub OnprovinceChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnprovinceChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property codepostal() As Global.System.String
        Get
            Return _codepostal
        End Get
        Set
            OncodepostalChanging(value)
            ReportPropertyChanging("codepostal")
            _codepostal = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("codepostal")
            OncodepostalChanged()
        End Set
    End Property

    Private _codepostal As Global.System.String
    Private Partial Sub OncodepostalChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodepostalChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property telephone() As Global.System.String
        Get
            Return _telephone
        End Get
        Set
            OntelephoneChanging(value)
            ReportPropertyChanging("telephone")
            _telephone = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("telephone")
            OntelephoneChanged()
        End Set
    End Property

    Private _telephone As Global.System.String
    Private Partial Sub OntelephoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntelephoneChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property telephone2() As Global.System.String
        Get
            Return _telephone2
        End Get
        Set
            Ontelephone2Changing(value)
            ReportPropertyChanging("telephone2")
            _telephone2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("telephone2")
            Ontelephone2Changed()
        End Set
    End Property

    Private _telephone2 As Global.System.String
    Private Partial Sub Ontelephone2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Ontelephone2Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fax() As Global.System.String
        Get
            Return _fax
        End Get
        Set
            OnfaxChanging(value)
            ReportPropertyChanging("fax")
            _fax = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fax")
            OnfaxChanged()
        End Set
    End Property

    Private _fax As Global.System.String
    Private Partial Sub OnfaxChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfaxChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property adremail() As Global.System.String
        Get
            Return _adremail
        End Get
        Set
            OnadremailChanging(value)
            ReportPropertyChanging("adremail")
            _adremail = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("adremail")
            OnadremailChanged()
        End Set
    End Property

    'Private _adremail As Global.System.String
    Private Partial Sub OnadremailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnadremailChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property noseq() As Nullable(Of Global.System.Int32)
        Get
            Return _noseq
        End Get
        Set
            OnnoseqChanging(value)
            ReportPropertyChanging("noseq")
            _noseq = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("noseq")
            OnnoseqChanged()
        End Set
    End Property

    Private _noseq As Nullable(Of Global.System.Int32)
    Private Partial Sub OnnoseqChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnnoseqChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property adresse2() As Global.System.String
        Get
            Return _adresse2
        End Get
        Set
            Onadresse2Changing(value)
            ReportPropertyChanging("adresse2")
            _adresse2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("adresse2")
            Onadresse2Changed()
        End Set
    End Property

    Private _adresse2 As Global.System.String
    Private Partial Sub Onadresse2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onadresse2Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property adresse3() As Global.System.String
        Get
            Return _adresse3
        End Get
        Set
            Onadresse3Changing(value)
            ReportPropertyChanging("adresse3")
            _adresse3 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("adresse3")
            Onadresse3Changed()
        End Set
    End Property

    Private _adresse3 As Global.System.String
    Private Partial Sub Onadresse3Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onadresse3Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property courant() As Global.System.String
        Get
            Return _courant
        End Get
        Set
            OncourantChanging(value)
            ReportPropertyChanging("courant")
            _courant = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("courant")
            OncourantChanged()
        End Set
    End Property

    Private _courant As Global.System.String
    Private Partial Sub OncourantChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncourantChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property dateadr() As Nullable(Of Global.System.DateTime)
        Get
            Return _dateadr
        End Get
        Set
            OndateadrChanging(value)
            ReportPropertyChanging("dateadr")
            _dateadr = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dateadr")
            OndateadrChanged()
        End Set
    End Property

    Private _dateadr As Nullable(Of Global.System.DateTime)
    Private Partial Sub OndateadrChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OndateadrChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property poste1() As Global.System.String
        Get
            Return _poste1
        End Get
        Set
            Onposte1Changing(value)
            ReportPropertyChanging("poste1")
            _poste1 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("poste1")
            Onposte1Changed()
        End Set
    End Property

    Private _poste1 As Global.System.String
    Private Partial Sub Onposte1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onposte1Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property poste2() As Global.System.String
        Get
            Return _poste2
        End Get
        Set
            Onposte2Changing(value)
            ReportPropertyChanging("poste2")
            _poste2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("poste2")
            Onposte2Changed()
        End Set
    End Property

    Private _poste2 As Global.System.String
    Private Partial Sub Onposte2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onposte2Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RowId() As Global.System.Guid
        Get
            Return _RowId
        End Get
        Set
            If (_RowId <> Value) Then
                OnRowIdChanging(value)
                ReportPropertyChanging("RowId")
                _RowId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("RowId")
                OnRowIdChanged()
            End If
        End Set
    End Property

    Private _RowId As Global.System.Guid
    Private Partial Sub OnRowIdChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnRowIdChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CardAvoModel", Name:="Avocats")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Avocats
    Inherits EntityObject
    #Region "Méthode de fabrique"

    ''' <summary>
    ''' Créez un nouvel objet Avocats.
    ''' </summary>
    ''' <param name="code">Valeur initiale de la propriété code.</param>
    ''' <param name="nom">Valeur initiale de la propriété nom.</param>
    ''' <param name="prenom">Valeur initiale de la propriété prenom.</param>
    ''' <param name="actpass">Valeur initiale de la propriété actpass.</param>
    ''' <param name="surveil">Valeur initiale de la propriété surveil.</param>
    Public Shared Function CreateAvocats(code As Global.System.String, nom As Global.System.String, prenom As Global.System.String, actpass As Global.System.String, surveil As Global.System.String) As Avocats
        Dim avocats as Avocats = New Avocats
        avocats.code = code
        avocats.nom = nom
        avocats.prenom = prenom
        avocats.actpass = actpass
        avocats.surveil = surveil
        Return avocats
    End Function

    #End Region

    #Region "Propriétés primitives"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property code() As Global.System.String
        Get
            Return _code
        End Get
        Set
            If (_code <> Value) Then
                OncodeChanging(value)
                ReportPropertyChanging("code")
                _code = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("code")
                OncodeChanged()
            End If
        End Set
    End Property

    Private _code As Global.System.String
    Private Partial Sub OncodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property sectbar() As Global.System.String
        Get
            Return _sectbar
        End Get
        Set
            OnsectbarChanging(value)
            ReportPropertyChanging("sectbar")
            _sectbar = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("sectbar")
            OnsectbarChanged()
        End Set
    End Property

    Private _sectbar As Global.System.String
    Private Partial Sub OnsectbarChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsectbarChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property mega() As Global.System.String
        Get
            Return _mega
        End Get
        Set
            OnmegaChanging(value)
            ReportPropertyChanging("mega")
            _mega = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("mega")
            OnmegaChanged()
        End Set
    End Property

    Private _mega As Global.System.String
    Private Partial Sub OnmegaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmegaChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property nom() As Global.System.String
        Get
            Return _nom
        End Get
        Set
            OnnomChanging(value)
            ReportPropertyChanging("nom")
            _nom = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("nom")
            OnnomChanged()
        End Set
    End Property

    Private _nom As Global.System.String
    Private Partial Sub OnnomChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnomChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property prenom() As Global.System.String
        Get
            Return _prenom
        End Get
        Set
            OnprenomChanging(value)
            ReportPropertyChanging("prenom")
            _prenom = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("prenom")
            OnprenomChanged()
        End Set
    End Property

    Private _prenom As Global.System.String
    Private Partial Sub OnprenomChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnprenomChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property actpass() As Global.System.String
        Get
            Return _actpass
        End Get
        Set
            OnactpassChanging(value)
            ReportPropertyChanging("actpass")
            _actpass = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("actpass")
            OnactpassChanged()
        End Set
    End Property

    Private _actpass As Global.System.String
    Private Partial Sub OnactpassChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnactpassChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property dateinscbarr() As Global.System.String
        Get
            Return _dateinscbarr
        End Get
        Set
            OndateinscbarrChanging(value)
            ReportPropertyChanging("dateinscbarr")
            _dateinscbarr = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("dateinscbarr")
            OndateinscbarrChanged()
        End Set
    End Property

    Private _dateinscbarr As Global.System.String
    Private Partial Sub OndateinscbarrChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndateinscbarrChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property payable() As Global.System.String
        Get
            Return _payable
        End Get
        Set
            OnpayableChanging(value)
            ReportPropertyChanging("payable")
            _payable = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("payable")
            OnpayableChanged()
        End Set
    End Property

    Private _payable As Global.System.String
    Private Partial Sub OnpayableChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpayableChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property adrcour() As Nullable(Of Global.System.Int32)
        Get
            Return _adrcour
        End Get
        Set
            OnadrcourChanging(value)
            ReportPropertyChanging("adrcour")
            _adrcour = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("adrcour")
            OnadrcourChanged()
        End Set
    End Property

    Private _adrcour As Nullable(Of Global.System.Int32)
    Private Partial Sub OnadrcourChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnadrcourChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property adrnonpay() As Nullable(Of Global.System.Int32)
        Get
            Return _adrnonpay
        End Get
        Set
            OnadrnonpayChanging(value)
            ReportPropertyChanging("adrnonpay")
            _adrnonpay = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("adrnonpay")
            OnadrnonpayChanged()
        End Set
    End Property

    Private _adrnonpay As Nullable(Of Global.System.Int32)
    Private Partial Sub OnadrnonpayChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnadrnonpayChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property codebar() As Global.System.String
        Get
            Return _codebar
        End Get
        Set
            OncodebarChanging(value)
            ReportPropertyChanging("codebar")
            _codebar = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("codebar")
            OncodebarChanged()
        End Set
    End Property

    Private _codebar As Global.System.String
    Private Partial Sub OncodebarChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodebarChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property comm() As Global.System.String
        Get
            Return _comm
        End Get
        Set
            OncommChanging(value)
            ReportPropertyChanging("comm")
            _comm = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("comm")
            OncommChanged()
        End Set
    End Property

    Private _comm As Global.System.String
    Private Partial Sub OncommChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncommChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property datemodif() As Nullable(Of Global.System.DateTime)
        Get
            Return _datemodif
        End Get
        Set
            OndatemodifChanging(value)
            ReportPropertyChanging("datemodif")
            _datemodif = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datemodif")
            OndatemodifChanged()
        End Set
    End Property

    Private _datemodif As Nullable(Of Global.System.DateTime)
    Private Partial Sub OndatemodifChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OndatemodifChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nas() As Global.System.String
        Get
            Return _nas
        End Get
        Set
            OnnasChanging(value)
            ReportPropertyChanging("nas")
            _nas = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nas")
            OnnasChanged()
        End Set
    End Property

    Private _nas As Global.System.String
    Private Partial Sub OnnasChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnasChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property depodirect() As Global.System.String
        Get
            Return _depodirect
        End Get
        Set
            OndepodirectChanging(value)
            ReportPropertyChanging("depodirect")
            _depodirect = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("depodirect")
            OndepodirectChanged()
        End Set
    End Property

    Private _depodirect As Global.System.String
    Private Partial Sub OndepodirectChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndepodirectChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property codeusager() As Global.System.String
        Get
            Return _codeusager
        End Get
        Set
            OncodeusagerChanging(value)
            ReportPropertyChanging("codeusager")
            _codeusager = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("codeusager")
            OncodeusagerChanged()
        End Set
    End Property

    Private _codeusager As Global.System.String
    Private Partial Sub OncodeusagerChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeusagerChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property motpasse1() As Global.System.String
        Get
            Return _motpasse1
        End Get
        Set
            Onmotpasse1Changing(value)
            ReportPropertyChanging("motpasse1")
            _motpasse1 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("motpasse1")
            Onmotpasse1Changed()
        End Set
    End Property

    Private _motpasse1 As Global.System.String
    Private Partial Sub Onmotpasse1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onmotpasse1Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property motpasse2() As Global.System.String
        Get
            Return _motpasse2
        End Get
        Set
            Onmotpasse2Changing(value)
            ReportPropertyChanging("motpasse2")
            _motpasse2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("motpasse2")
            Onmotpasse2Changed()
        End Set
    End Property

    Private _motpasse2 As Global.System.String
    Private Partial Sub Onmotpasse2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onmotpasse2Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property factweb() As Global.System.String
        Get
            Return _factweb
        End Get
        Set
            OnfactwebChanging(value)
            ReportPropertyChanging("factweb")
            _factweb = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("factweb")
            OnfactwebChanged()
        End Set
    End Property

    Private _factweb As Global.System.String
    Private Partial Sub OnfactwebChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfactwebChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property confweb() As Global.System.String
        Get
            Return _confweb
        End Get
        Set
            OnconfwebChanging(value)
            ReportPropertyChanging("confweb")
            _confweb = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("confweb")
            OnconfwebChanged()
        End Set
    End Property

    Private _confweb As Global.System.String
    Private Partial Sub OnconfwebChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnconfwebChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property villeref() As Global.System.String
        Get
            Return _villeref
        End Get
        Set
            OnvillerefChanging(value)
            ReportPropertyChanging("villeref")
            _villeref = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("villeref")
            OnvillerefChanged()
        End Set
    End Property

    Private _villeref As Global.System.String
    Private Partial Sub OnvillerefChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnvillerefChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usermodif() As Global.System.String
        Get
            Return _usermodif
        End Get
        Set
            OnusermodifChanging(value)
            ReportPropertyChanging("usermodif")
            _usermodif = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usermodif")
            OnusermodifChanged()
        End Set
    End Property

    Private _usermodif As Global.System.String
    Private Partial Sub OnusermodifChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusermodifChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property surveil() As Global.System.String
        Get
            Return _surveil
        End Get
        Set
            OnsurveilChanging(value)
            ReportPropertyChanging("surveil")
            _surveil = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("surveil")
            OnsurveilChanged()
        End Set
    End Property

    Private _surveil As Global.System.String
    Private Partial Sub OnsurveilChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsurveilChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property neq() As Global.System.String
        Get
            Return _neq
        End Get
        Set
            OnneqChanging(value)
            ReportPropertyChanging("neq")
            _neq = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("neq")
            OnneqChanged()
        End Set
    End Property

    Private _neq As Global.System.String
    Private Partial Sub OnneqChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnneqChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CardAvoModel", Name:="infodistrict")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class infodistrict
    Inherits EntityObject
    #Region "Méthode de fabrique"

    ''' <summary>
    ''' Créez un nouvel objet infodistrict.
    ''' </summary>
    ''' <param name="code">Valeur initiale de la propriété code.</param>
    ''' <param name="nodist">Valeur initiale de la propriété nodist.</param>
    Public Shared Function Createinfodistrict(code As Global.System.String, nodist As Global.System.Int32) As infodistrict
        Dim infodistrict as infodistrict = New infodistrict
        infodistrict.code = code
        infodistrict.nodist = nodist
        Return infodistrict
    End Function

    #End Region

    #Region "Propriétés primitives"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property code() As Global.System.String
        Get
            Return _code
        End Get
        Set
            If (_code <> Value) Then
                OncodeChanging(value)
                ReportPropertyChanging("code")
                _code = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("code")
                OncodeChanged()
            End If
        End Set
    End Property

    Private _code As Global.System.String
    Private Partial Sub OncodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property nodist() As Global.System.Int32
        Get
            Return _nodist
        End Get
        Set
            OnnodistChanging(value)
            ReportPropertyChanging("nodist")
            _nodist = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("nodist")
            OnnodistChanged()
        End Set
    End Property

    Private _nodist As Global.System.Int32
    Private Partial Sub OnnodistChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnnodistChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CardAvoModel", Name:="infomega")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class infomega
    Inherits EntityObject
    #Region "Méthode de fabrique"

    ''' <summary>
    ''' Créez un nouvel objet infomega.
    ''' </summary>
    ''' <param name="code">Valeur initiale de la propriété code.</param>
    ''' <param name="francais">Valeur initiale de la propriété francais.</param>
    ''' <param name="anglais">Valeur initiale de la propriété anglais.</param>
    ''' <param name="autres">Valeur initiale de la propriété autres.</param>
    ''' <param name="experience">Valeur initiale de la propriété experience.</param>
    ''' <param name="details">Valeur initiale de la propriété details.</param>
    ''' <param name="mega">Valeur initiale de la propriété mega.</param>
    ''' <param name="tarification">Valeur initiale de la propriété tarification.</param>
    ''' <param name="art486">Valeur initiale de la propriété art486.</param>
    ''' <param name="art672">Valeur initiale de la propriété art672.</param>
    ''' <param name="art684">Valeur initiale de la propriété art684.</param>
    ''' <param name="districthab">Valeur initiale de la propriété districthab.</param>
    ''' <param name="commentaire">Valeur initiale de la propriété commentaire.</param>
    ''' <param name="dateinsc">Valeur initiale de la propriété dateinsc.</param>
    ''' <param name="usermodif">Valeur initiale de la propriété usermodif.</param>
    Public Shared Function Createinfomega(code As Global.System.String, francais As Global.System.String, anglais As Global.System.String, autres As Global.System.String, experience As Global.System.Int32, details As Global.System.String, mega As Global.System.String, tarification As Global.System.String, art486 As Global.System.String, art672 As Global.System.String, art684 As Global.System.String, districthab As Global.System.String, commentaire As Global.System.String, dateinsc As Global.System.DateTime, usermodif As Global.System.String) As infomega
        Dim infomega as infomega = New infomega
        infomega.code = code
        infomega.francais = francais
        infomega.anglais = anglais
        infomega.autres = autres
        infomega.experience = experience
        infomega.details = details
        infomega.mega = mega
        infomega.tarification = tarification
        infomega.art486 = art486
        infomega.art672 = art672
        infomega.art684 = art684
        infomega.districthab = districthab
        infomega.commentaire = commentaire
        infomega.dateinsc = dateinsc
        infomega.usermodif = usermodif
        Return infomega
    End Function

    #End Region

    #Region "Propriétés primitives"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property code() As Global.System.String
        Get
            Return _code
        End Get
        Set
            If (_code <> Value) Then
                OncodeChanging(value)
                ReportPropertyChanging("code")
                _code = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("code")
                OncodeChanged()
            End If
        End Set
    End Property

    Private _code As Global.System.String
    Private Partial Sub OncodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property francais() As Global.System.String
        Get
            Return _francais
        End Get
        Set
            OnfrancaisChanging(value)
            ReportPropertyChanging("francais")
            _francais = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("francais")
            OnfrancaisChanged()
        End Set
    End Property

    Private _francais As Global.System.String
    Private Partial Sub OnfrancaisChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfrancaisChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property anglais() As Global.System.String
        Get
            Return _anglais
        End Get
        Set
            OnanglaisChanging(value)
            ReportPropertyChanging("anglais")
            _anglais = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("anglais")
            OnanglaisChanged()
        End Set
    End Property

    Private _anglais As Global.System.String
    Private Partial Sub OnanglaisChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnanglaisChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property autres() As Global.System.String
        Get
            Return _autres
        End Get
        Set
            OnautresChanging(value)
            ReportPropertyChanging("autres")
            _autres = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("autres")
            OnautresChanged()
        End Set
    End Property

    Private _autres As Global.System.String
    Private Partial Sub OnautresChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnautresChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property experience() As Global.System.Int32
        Get
            Return _experience
        End Get
        Set
            OnexperienceChanging(value)
            ReportPropertyChanging("experience")
            _experience = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("experience")
            OnexperienceChanged()
        End Set
    End Property

    Private _experience As Global.System.Int32
    Private Partial Sub OnexperienceChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnexperienceChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property details() As Global.System.String
        Get
            Return _details
        End Get
        Set
            OndetailsChanging(value)
            ReportPropertyChanging("details")
            _details = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("details")
            OndetailsChanged()
        End Set
    End Property

    Private _details As Global.System.String
    Private Partial Sub OndetailsChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndetailsChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property mega() As Global.System.String
        Get
            Return _mega
        End Get
        Set
            OnmegaChanging(value)
            ReportPropertyChanging("mega")
            _mega = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("mega")
            OnmegaChanged()
        End Set
    End Property

    Private _mega As Global.System.String
    Private Partial Sub OnmegaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmegaChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property tarification() As Global.System.String
        Get
            Return _tarification
        End Get
        Set
            OntarificationChanging(value)
            ReportPropertyChanging("tarification")
            _tarification = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("tarification")
            OntarificationChanged()
        End Set
    End Property

    Private _tarification As Global.System.String
    Private Partial Sub OntarificationChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntarificationChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property art486() As Global.System.String
        Get
            Return _art486
        End Get
        Set
            Onart486Changing(value)
            ReportPropertyChanging("art486")
            _art486 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("art486")
            Onart486Changed()
        End Set
    End Property

    Private _art486 As Global.System.String
    Private Partial Sub Onart486Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onart486Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property art672() As Global.System.String
        Get
            Return _art672
        End Get
        Set
            Onart672Changing(value)
            ReportPropertyChanging("art672")
            _art672 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("art672")
            Onart672Changed()
        End Set
    End Property

    Private _art672 As Global.System.String
    Private Partial Sub Onart672Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onart672Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property art684() As Global.System.String
        Get
            Return _art684
        End Get
        Set
            Onart684Changing(value)
            ReportPropertyChanging("art684")
            _art684 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("art684")
            Onart684Changed()
        End Set
    End Property

    Private _art684 As Global.System.String
    Private Partial Sub Onart684Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onart684Changed()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property districthab() As Global.System.String
        Get
            Return _districthab
        End Get
        Set
            OndistricthabChanging(value)
            ReportPropertyChanging("districthab")
            _districthab = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("districthab")
            OndistricthabChanged()
        End Set
    End Property

    Private _districthab As Global.System.String
    Private Partial Sub OndistricthabChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndistricthabChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property commentaire() As Global.System.String
        Get
            Return _commentaire
        End Get
        Set
            OncommentaireChanging(value)
            ReportPropertyChanging("commentaire")
            _commentaire = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("commentaire")
            OncommentaireChanged()
        End Set
    End Property

    Private _commentaire As Global.System.String
    Private Partial Sub OncommentaireChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncommentaireChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property dateinsc() As Global.System.DateTime
        Get
            Return _dateinsc
        End Get
        Set
            OndateinscChanging(value)
            ReportPropertyChanging("dateinsc")
            _dateinsc = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dateinsc")
            OndateinscChanged()
        End Set
    End Property

    Private _dateinsc As Global.System.DateTime
    Private Partial Sub OndateinscChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndateinscChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property usermodif() As Global.System.String
        Get
            Return _usermodif
        End Get
        Set
            OnusermodifChanging(value)
            ReportPropertyChanging("usermodif")
            _usermodif = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("usermodif")
            OnusermodifChanged()
        End Set
    End Property

    Private _usermodif As Global.System.String
    Private Partial Sub OnusermodifChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusermodifChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property datemodif() As Nullable(Of Global.System.DateTime)
        Get
            Return _datemodif
        End Get
        Set
            OndatemodifChanging(value)
            ReportPropertyChanging("datemodif")
            _datemodif = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datemodif")
            OndatemodifChanged()
        End Set
    End Property

    Private _datemodif As Nullable(Of Global.System.DateTime)
    Private Partial Sub OndatemodifChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OndatemodifChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property sectbar() As Global.System.String
        Get
            Return _sectbar
        End Get
        Set
            OnsectbarChanging(value)
            ReportPropertyChanging("sectbar")
            _sectbar = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("sectbar")
            OnsectbarChanged()
        End Set
    End Property

    Private _sectbar As Global.System.String
    Private Partial Sub OnsectbarChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsectbarChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CardAvoModel", Name:="inhpra")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class inhpra
    Inherits EntityObject
    #Region "Méthode de fabrique"

    ''' <summary>
    ''' Créez un nouvel objet inhpra.
    ''' </summary>
    ''' <param name="code">Valeur initiale de la propriété code.</param>
    ''' <param name="datedeb">Valeur initiale de la propriété datedeb.</param>
    ''' <param name="datefin">Valeur initiale de la propriété datefin.</param>
    Public Shared Function Createinhpra(code As Global.System.String, datedeb As Global.System.DateTime, datefin As Global.System.DateTime) As inhpra
        Dim inhpra as inhpra = New inhpra
        inhpra.code = code
        inhpra.datedeb = datedeb
        inhpra.datefin = datefin
        Return inhpra
    End Function

    #End Region

    #Region "Propriétés primitives"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property code() As Global.System.String
        Get
            Return _code
        End Get
        Set
            If (_code <> Value) Then
                OncodeChanging(value)
                ReportPropertyChanging("code")
                _code = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("code")
                OncodeChanged()
            End If
        End Set
    End Property

    Private _code As Global.System.String
    Private Partial Sub OncodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datedeb() As Global.System.DateTime
        Get
            Return _datedeb
        End Get
        Set
            OndatedebChanging(value)
            ReportPropertyChanging("datedeb")
            _datedeb = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datedeb")
            OndatedebChanged()
        End Set
    End Property

    Private _datedeb As Global.System.DateTime
    Private Partial Sub OndatedebChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatedebChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datefin() As Global.System.DateTime
        Get
            Return _datefin
        End Get
        Set
            OndatefinChanging(value)
            ReportPropertyChanging("datefin")
            _datefin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datefin")
            OndatefinChanged()
        End Set
    End Property

    Private _datefin As Global.System.DateTime
    Private Partial Sub OndatefinChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatefinChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property comm() As Global.System.String
        Get
            Return _comm
        End Get
        Set
            OncommChanging(value)
            ReportPropertyChanging("comm")
            _comm = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("comm")
            OncommChanged()
        End Set
    End Property

    Private _comm As Global.System.String
    Private Partial Sub OncommChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncommChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' Aucune documentation sur les métadonnées n'est disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CardAvoModel", Name:="lettremega")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class lettremega
    Inherits EntityObject
    #Region "Méthode de fabrique"

    ''' <summary>
    ''' Créez un nouvel objet lettremega.
    ''' </summary>
    ''' <param name="codeavo">Valeur initiale de la propriété codeavo.</param>
    ''' <param name="dateenvoi">Valeur initiale de la propriété dateenvoi.</param>
    Public Shared Function Createlettremega(codeavo As Global.System.String, dateenvoi As Global.System.DateTime) As lettremega
        Dim lettremega as lettremega = New lettremega
        lettremega.codeavo = codeavo
        lettremega.dateenvoi = dateenvoi
        Return lettremega
    End Function

    #End Region

    #Region "Propriétés primitives"

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property codeavo() As Global.System.String
        Get
            Return _codeavo
        End Get
        Set
            If (_codeavo <> Value) Then
                OncodeavoChanging(value)
                ReportPropertyChanging("codeavo")
                _codeavo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("codeavo")
                OncodeavoChanged()
            End If
        End Set
    End Property

    Private _codeavo As Global.System.String
    Private Partial Sub OncodeavoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeavoChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property dateenvoi() As Global.System.DateTime
        Get
            Return _dateenvoi
        End Get
        Set
            OndateenvoiChanging(value)
            ReportPropertyChanging("dateenvoi")
            _dateenvoi = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dateenvoi")
            OndateenvoiChanged()
        End Set
    End Property

    Private _dateenvoi As Global.System.DateTime
    Private Partial Sub OndateenvoiChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndateenvoiChanged()
    End Sub

    ''' <summary>
    ''' Aucune documentation sur les métadonnées n'est disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property datereception() As Nullable(Of Global.System.DateTime)
        Get
            Return _datereception
        End Get
        Set
            OndatereceptionChanging(value)
            ReportPropertyChanging("datereception")
            _datereception = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datereception")
            OndatereceptionChanged()
        End Set
    End Property

    Private _datereception As Nullable(Of Global.System.DateTime)
    Private Partial Sub OndatereceptionChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OndatereceptionChanged()
    End Sub

    #End Region

End Class

#End Region


